<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

# Exercise 1

Purely from memory, write short descriptions of the following terms:

| Term    |  Brief description   |   
| :--- | ---: |
| Subsetting  | This is to select from a list or array   |
| Indexing   |  An index is the position of the data in the list or array  |
| Slicing   |  Slicing is to select multiple data points in the list or array  |
| Masking   |  Masking decides test for the data in the list or array is true or false based on a given condition  |

In [11]:
#Exercise 2
import numpy as np                        #import numpy

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_num = np_array_2d[:,0].astype(int)                 #getting first argument in each sublist 
                                                            #and putting it in another list as integers

np_mask = np_array_num %2 == 1                              #creating a mask of the numbers that are odd
                                                            #by checking if the modulus of the number returns
                                                            #a remainder of 1


print(np_array_2d[np_mask,1])                               #printing the original list
                                                            #with the condition given by the mask
                                                            #and specifically only printing the second argument
                                                            #in each subset, which would be the letters

['A' 'C' 'E' 'G' 'I']


In [65]:
#exercise 3

num = np.array([[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]])

mask1 = num <50                   #first conditional mask
mask2 = num >50                   #second conditional mask
mask3 = num == 50                 #third conditional mask

num[mask1] = -1                   #first mask changes
num[mask2] = 1                    #second mask change
num[mask3] = 0                    #third mask change

print(num)                        #output

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
